baseURL = "https://deislabs.io/"
languageCode = "en-us"
title = "Deis Labs"
theme = "fresh"
disableHugoGeneratorInject = true

[markup]
  [markup.highlight]
    style = "tomorrow-night"

[params]
  image = "images/twitter-card.png"
  
  [params.font]
  name = "Nunito Sans"
  sizes = [
    400.0,
    800.0
  ]

  [params.hero]
  title = "Cloud Native Developer Experience"
  subtitle = "Development on the leading edge of the adoption curve can be rocky. Deis Labs is here to help make you more productive."

  [params.navbarlogo]
    link = "/"
    image = "deislabs.svg"

  [params.section1]
  title = "Developer Focus"
  subtitle = "Bridging the gap between shiny tech and a great developer experience"

    [[params.section1.tiles]]
    title = "Akri"
    icon = "akri"
    text = "A Kubernetes Resource Interface for the Edge, Akri exposes devices as resources in Kubernetes."
    url = "https://github.com/deislabs/akri"

    [[params.section1.tiles]]
    title = "Bindle"
    icon = "bindle"
    text = "Aggregate Object Storage for Collections - a Rust project we made as part of our WebAssembly research."
    url = "https://github.com/deislabs/bindle"

    [[params.section1.tiles]]
    title = "Brigade"
    icon = "brigade"
    text = "Create event-driven workflows and pipelines for your infrastructure, through scriptable, automated tasks."
    url = "https://brigade.sh"
    badge = "cncf"
    badgecolor = "teal"

    [[params.section1.tiles]]
    title = "CNAB"
    icon = "cnab"
    text = "CNABs facilitate the bundling, installing and managing of container-native apps â€” and their coupled services."
    url = "/cnab/"

    [[params.section1.tiles]]
    title = "Draft"
    icon = "draft"
    text = "A tool to quickly build & run Kubernetes apps, to streamline the dev process."
    url = "https://draft.sh"
    badge = "archived"
    badgecolor = "gray"

    [[params.section1.tiles]]
    title = "Duffle"
    icon = "duffle"
    text = "A tool that installs and manages distributed app bundles (CNABs)."
    url = "https://duffle.sh"

    [[params.section1.tiles]]
    title = "Go Lua"
    icon = "golua"
    text = "A Lua 5.3 engine implemented in Go."
    url = "https://github.com/Azure/golua"
    badge = "archived"
    badgecolor = "gray"

    [[params.section1.tiles]]
    title = "Helm"
    icon = "helm"
    text = "The package manager for Kubernetes. Created by Deis Labs members in 2015, now a CNCF graduated project."
    url = "https://helm.sh"
    badge = "cncf"
    badgecolor = "teal"

    [[params.section1.tiles]]
    title = "Krustlet"
    icon = "krustlet"
    text = "Krustlet is a tool to run WebAssembly workloads natively on Kubernetes."
    url = "https://krustlet.dev"

    [[params.section1.tiles]]
    title = "ORAS"
    icon = "oras"
    text = "OCI (Open Container Initiative) Registry As Storage."
    url = "https://github.com/deislabs/oras"

    [[params.section1.tiles]]
    title = "Porter"
    icon = "porter"
    text = "Porter makes authoring CNAB bundles easier, handling your app and everything you need to deploy with it."
    url = "https://porter.sh"
    badge = "cncf"
    badgecolor = "teal"

    [[params.section1.tiles]]
    title = "Mystikos"
    icon = "mystikos"
    text = "Mystikos is a set of tools for running applications in a hardware trusted execution environment (TEE)."
    url = "https://github.com/deislabs/mystikos"

    [[params.section1.tiles]]
    title = "WAGI"
    icon = "wagi"
    text = "Write HTTP handlers in WebAssembly with a minimal amount of work."
    url = "https://github.com/deislabs/wagi"


  [params.footer]
  logo = "deislabs.png"
  bulmalogo = false

    [[params.footer.socialmedia]]
    link = "https://github.com/deislabs"
    icon = "github"

    [[params.footer.socialmedia]]
    link = "https://twitter.com/deislabs"
    icon = "twitter"
  
  [[params.navbar]]
  title = "About"
  url = "/about"

  [[params.navbar]]
  title = "Blog"
  url = "/posts"

  [[params.navbar]]
  title = "Projects"
  url = "https://deislabs.io/#projects"
